### ISSUE TITLE
Multiple Mails over Single SMTP Connection

### ISSUE THREAD

**Issue by codingrogue** [go-gomail/gomail#33] opened 2015-05-05 13:03 UTC
I wonder if it's possible to send multiple emails over one SMTP connection and if it would improve the performance? I just tested your library, it's very smooth to use but it takes about 8 seconds to send 10 mails with the same mailer object.

**Comment by alexcesaro** [comment] 2015-05-10 16:19
Duplicate of #10.

**Closed by alexcesaro** 2015-05-10 16:19 UTC
